### ISSUE TITLE
Impossible to compile anything other than MSC class

### ISSUE THREAD

**Issue by DrZlo13** [atanisoft/esp32usb#1]
Currently the "Task configuration" part of Kconfig depends on ESPUSB_MSC flag, so project cannot be compiled unless you select MSC class.

**Comment by atanisoft** [comment]
Sorry about that, I usually only use this for MSC and CDC in my projects. It looks like the config had an extra dependency that shouldn't have been there. I've updated the code on master to remove this dependency.
