### ISSUE TITLE
Enabling HID driver results in compilation failure

### ISSUE THREAD

**Issue by Huckies** [atanisoft/esp32usb#2]
Hi there, thanks for providing such a useful component, but I encountered some problems when deploying.

I tried both esp-idf v4.4 stable version(the latest release) and the master branch which seems to be a beta version of esp-idf 5.0, they both failed compiling.

The chip is esp32s3, I followed the instruction and put your repo under ${IDF_PATH}/components then use idf.py menuconfig to open the esp32usb with it’s hid  component and leave the original tinyusb closed.

I managed to fix some missing header problems but the ‘std::string’ in function declarations blocked me, would you please update this repo to fix it? Thanks a lot!

**Comment by atanisoft** [comment]
@Huckies This library should *NOT* be under `${IDF_PATH}` but instead in your project's components tree. This is also only compatible with C++ code and not C code as used in IDF.

If you can share a bit more information on your project I should be able to help further on any issues.

**Comment by Huckies** [comment]
@atanisoft Thanks for replying! What should I do to use C++ code? I've used arduino-as-component before but still have no idea the difference between them under IDF.

**Comment by atanisoft** [comment]
This is a pure IDF component with no Arduino dependencies.

To use this as C++ vs C, rename your `main.c` to `main.cpp` and update the reference in `CMakeLists.txt`. Whichever file(s) use the code from this library should have their filenames ending in `cpp` instead of `c`.

**Comment by Huckies** [comment]
@atanisoft Yeah I followed that, so the project directory look likes this now [https://github.com/Huckies/Debugging/blob/master/Screenshot%202022-02-13%2012.03.26.png](url)

My configuration of esp32usb in idf.py menuconfig looks like this, with TinyUSB stack(the one comes with IDF) unchecked [https://github.com/Huckies/Debugging/blob/master/Screenshot%202022-02-13%2012.06.32.png](url)

But I'm still getting these errors:[https://github.com/Huckies/Debugging/blob/master/Screenshot%202022-02-13%2012.02.23.png](url)

**Comment by atanisoft** [comment]
From the errors it looks like HID is missing some config flags. I'll see what I can come up with.

**Comment by Huckies** [comment]
It's the missing part
```
  /// HID Protocol
  typedef enum
  {
    HID_PROTOCOL_NONE = 0,     ///< None
    HID_PROTOCOL_KEYBOARD = 1, ///< Keyboard
    HID_PROTOCOL_MOUSE = 2     ///< Mouse
  } hid_protocol_type_t;
```
in `esp32usb/src/tinyusb/src/class/hid/hid.h` caused the problem, adding it as well as its include path to `esp32usb/CMakeLists.txt` fixed the problem.

But I still can't figure out the problem with `desc_hid_report`, the macro thing looks strange.

**Comment by atanisoft** [comment]
`hid_protocol_type_t` was renamed to `hid_interface_protocol_enum_t` and so `HID_PROTOCOL_NONE` should now be `HID_ITF_PROTOCOL_NONE`. As for `desc_hid_report` it is being referenced before declaration.

Give the latest commit a try.

**Comment by Huckies** [comment]
Yeah it do fix the problems mentioned above, but in `usb.cpp`, line 296&297
```
  TUD_HID_REPORT_DESC_CONSUMER( HID_REPORT_ID(REPORT_ID_CONSUMER_CONTROL )),
  TUD_HID_REPORT_DESC_GAMEPAD ( HID_REPORT_ID(REPORT_ID_GAMEPAD          ))
```
is added to tinyusb component after release 0.12.0 so currently it's not able to use. Also `usb.cpp` needs a header file `hid.h` when HID function is enabled in menuconfig.

Furthermore, while it completes compiling errors still occur when linking. Sorry for the inconvenience that I can't get them highlighted since they are not compiling errors.
![Screenshot 2022-02-14 9 49 15](https://user-images.githubusercontent.com/46043032/153786717-c8ec61d6-a799-4205-8613-3ea419066467.png)

**Comment by atanisoft** [comment]
> is added to tinyusb component after release 0.12.0 so currently it's not able to use.

The embedded TinyUSB is currently pinned to 0.12.0 tagged release. I pulled this from the HID example tree.

> Also `usb.cpp` needs a header file `hid.h` when HID function is enabled in menuconfig.

https://github.com/atanisoft/esp32usb/blob/8423db0bb105cf3ff44842e50f04f52223091592/src/usb.cpp#L24-L26

> Sorry for the inconvenience that I can't get them highlighted since they are not compiling errors.

`gpio_output_set_high` is an ESP-IDF function that looks like they moved to a new header file, I'll add the required header for fixing that.

As for `tud_hid_get_report_cb`, `tud_hid_set_report_cb` and `tud_hid_descriptor_report_cb` these are application specific but I'll provide a default implementation but you will likely need to override the functionality to suit your application's needs.

**Comment by Huckies** [comment]
Appreciate your efforts! I'm kinda lost in the tinyusb codes, 3*interfaces with 5*endpoints work, but 4*interfaces with 6*endpoints/3*interfaces with 6*endpoints fail all the time, I've checked the code for many times.

Whatever, I'll give another try and hope the esp32usb repo works as silk. Thanks again!

**Comment by Huckies** [comment]
While I still cannot figure out all the errors when compiling this repo, I manage to build my own device base on the tinyusb stack. This repo do help me a lot understanding, thanks again for offering such a "code abstraction layer".
