### ISSUE TITLE
incorrect lenght for the string inside string descriptor

### ISSUE THREAD

**Issue by GiaGoose** [atanisoft/esp32usb#3]
in configure_usb_descriptor_str assign the length of the string to MAX_DESCRIPTOR_LEN not the actual length of the string.
in tud_descriptor_string_cb will always return a descritpor with  incorrect length

**Comment by atanisoft** [comment]
I agree that https://github.com/atanisoft/esp32usb/blob/bfb284784f8598ed57b61cf738ab4f5c2afe9d21/src/usb.cpp#L389 looks possibly incorrect and may copy outside the incoming string. I'll do some testing and adjust accordingly. This may influence the value returned by `tud_descriptor_string_cb` which also needs an added bounds check for `MAX_DESCRIPTOR_LEN`
